### ISSUE TITLE
Optional support for non-published properties and fields

### ISSUE THREAD

**Issue by beNative** [MahdiSafsafi/zcontrols#2]
I had a play with your great component and was glad to see that you use the new RTTI features, which makes it possible to expose a lot more than just published properties. I did a little test and with only a minor tweak in the sources the control could also show private, protected and public fields and properties. Maybe you should consider making this an optional feature.
As of now I am not aware of any commercial or open source object inspector control that is able to do that.

**Comment by MahdiSafsafi** [comment]
Thank you. I will consider it as a feature request.
