### ISSUE TITLE
Use the TzObjectInspector component as the Configuration Editor.

### ISSUE THREAD

**Issue by JuanCarlosMagana** [MahdiSafsafi/zcontrols#21]
This is not a issue, it is a question.
Will there be any way to use the TzObjectInspector component to modify the configuration options of my program?
I do not want to modify the properties of the objects, but I can add configuration options and modify them. As delphi does. If not, this could be another good component that you could add to zControls.
Greetings.
Sorry my bad  english.

![options inspector](https://user-images.githubusercontent.com/38815370/39398617-ef5cf752-4ad5-11e8-9b96-47df3bc9cc2e.png)

**Comment by MahdiSafsafi** [comment]
zObjectInspector works only with TObject descending class. If your configuration is OOP then yes you can use zObjectInspector to edit your configuration properties.
