### ISSUE TITLE
Using of the inspector control would block TAB key for the entire windows 7 system.

### ISSUE THREAD

**Issue by edwinyzh** [MahdiSafsafi/zcontrols#22]
If you compile and run the supplied demo,  then switch any other programs else, for example, your text editor or the Delphi IDE, you press TAB and it no longer works. you quit the demo program and the issue goes away.

I have the same issue in the program that uses TZObjectInspector.
That's a wired issue, but the inspector control is great!

**Comment by pyscripter** [comment]
The problem is in 

```
procedure TzCustomObjInspector.CreateWnd;
begin
  inherited;
  FSelectedIndex := -1;
  if not(csDesigning in ComponentState) then
    RegisterHotKey(Handle, 0, 0, VK_TAB);
end;
```
and
procedure TzCustomObjInspector.WMHotKey(var Msg: TWMHotKey);


I am not exactly sure what is the purpose of this.   If you comment out the RegisterHotKey call you will not have this issue.

**Comment by MahdiSafsafi** [comment]
@pyscripter The purpose of tab is to allow searching for properties. For example press TAB and start entering some text such **Ca** and TZObjectInspector will jump to **Caption** property. 

@edwinyzh I just started investigating the issue ... and you're right ! same scenario happens to me.
