### ISSUE TITLE
Access violation after editing a property and moving the focus by key (up, down).

### ISSUE THREAD

**Issue by pyscripter** [MahdiSafsafi/zcontrols#23]
Easy to reproduce.
Edit a string property say by typing a few characters and without pressing Enter, press up/down key.
procedure.   The problem is in the method below.
```
TzCustomObjInspector.UpdateEditControl(const SetValue: Boolean);
var
  PItem: PPropItem;
  BtnWidth: Integer;
  LTxtValRect: TRect;
begin
  if Assigned(FPropInspEdit) then
    if Assigned(FPropInspEdit.Parent) then
    begin
      FPropInspEdit.PropInfo := nil;
      FPropInspEdit.Visible := False;
    end;
```

It first sets PropInfo to nil and then Visible to false.  The second statement results in a KILLFOCUS message which calls DoSetValueFromEdit with FPropInfo equal to nil.

** Solution: **
Reverse the statements, so that first the value gets updated and then PropInfo is set to nil.
 i.e.

```
  if Assigned(FPropInspEdit) then
    if Assigned(FPropInspEdit.Parent) then
    begin
      FPropInspEdit.Visible := False;
      FPropInspEdit.PropInfo := nil;
    end;

```

**Comment by MahdiSafsafi** [comment]
Thanks man !
