### ISSUE TITLE
Allow localization of True/False

### ISSUE THREAD

**Issue by pyscripter** [MahdiSafsafi/zcontrols#27]
I am reopening issue #25 because I found a couple of issues with the solution I suggested there and was implemented.

Suggested changes:

a) Replace BooleanToStr with the following:
```
function BooleanToStr(B: Boolean): string;
begin
  if B then
    Result := STrueValue
  else
    Result := SFalseValue;
end;
```

The reason is that the use of the resource strings in the constant  does not work because presumably the compiler initializes the constant when the program is loaded and the translated strings are not picked up.

b)  Currently BooleanToStr is only used in set properties and not in Boolean properties.  Modify the TzCustomValueManager.GetValueName as follows.

```
  if PItem.IsSetElement then
  begin
    Result := BooleanToStr(SetEnumToBoolean(GetEnumOrdValue(Value), PItem.SetElementValue));
    Exit;
  end
  else if (Value.TypeInfo = TypeInfo(Boolean)) then  //  added this if block
  begin
    Result := BooleanToStr(GetValueAs<Boolean>(Value));
    Exit;
  end
```

**Comment by MahdiSafsafi** [comment]
Hi,
Thanks for the explanation.
Can you please make a PR?

**Comment by pyscripter** [comment]
Done #28
