### ISSUE TITLE
Exception when removing TzObjectInspector from form at design time

### ISSUE THREAD

**Issue by pyscripter** [MahdiSafsafi/zcontrols#31]
I am seeing an exception when deleting a TzObjectInspector from a form at design time.\
Solution
Change  TzScrollObjInspectorList.UpdateScrollBar to:

```
procedure TzScrollObjInspectorList.UpdateScrollBar;
begin
  if Assigned(Parent) and not(csDestroying in ComponentState) then
  begin
    FSI.cbSize := SizeOf(FSI);
    FSI.fMask := SIF_RANGE or SIF_PAGE;
    FSI.nMin := 0;
    FSI.nMax := VisiblePropCount - 1;
    FSI.nPage := GetMaxItemCount;
    SetScrollInfo(Handle, SB_VERT, FSI, False);
    InvalidateNC;
  end;
end;
```

**Comment by MahdiSafsafi** [comment]
Sorry for the delay. 
Yes, you're right, it happened to me on Delphi 10.3. I don't remember that I got an AV when removing the Inspector on Delphi XE series. Perhaps there was a change on their designer. 
Thanks man ! you did a great job :)
