### ISSUE TITLE
Feature request: property editor for keyboard shortcuts

### ISSUE THREAD

**Issue by beNative** [MahdiSafsafi/zcontrols#5]
A dedicated dropdown combobox for keyboard shortcut properties (TShortCut) is missing.

**Comment by MahdiSafsafi** [comment]
Hi,
Can you please send more details cause I didn't understand exactly your issue.
Thanks.

**Comment by beNative** [comment]
Hi, 
Now the value for a property of type `TShortCut` is displayed as an integer. It would be nice if you could select a shortcut from its text representation (e.g. CTRL-ALT-F1) like the Delphi object inspector does.

**Comment by MahdiSafsafi** [comment]
Thanks, now I understand clearly what do you mean.
